version: '3.8'

services:
  # Node.js Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: demo-api-app-prod
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
